volumes:
  soon-tm-data:
    external: true
  pg-admin:
    external: true
services:
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_ACCOUNTS_HOST: http://localhost:8000
      REACT_APP_REMINDERS_HOST: http://localhost:8001
      REACT_APP_CONTACTS_HOST: http://localhost:8002
      REACT_APP_TEMPLATES_HOST: http://localhost:8003
  db:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    environment:
      - POSTGRES_MULTIPLE_DATABASES=accounts, reminders, contacts, templates
      - POSTGRES_PASSWORD=password
    ports:
      - "15432:5432"
    volumes:
      - soon-tm-data:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: soontm@soontm.com
      PGADMIN_DEFAULT_PASSWORD: ghostbusters
      PGADMIN_DISABLE_POSTFIX: 1
  users_api:
    build:
      context: users_service
      dockerfile: Dockerfile.dev
    environment:
      SIGNING_KEY: ghostbusters
      DATABASE_URL: postgresql://postgres:password@db:5432/accounts
      WAIT_HOSTS: db:5432
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./users_service:/app
  reminders_api:
    build:
      context: reminders_service
      dockerfile: Dockerfile.dev
    environment:
      SIGNING_KEY: ghostbusters
      DATABASE_URL: postgresql://postgres:password@db:5432/reminders
      WAIT_HOSTS: db:5432
      PORT: 8001
      COMPILER_ROUTE: Jj94E9GRLl6a0pAjIjVp1jLG3LAdyagN
    ports:
      - "8001:8000"
    volumes:
      - ./reminders_service:/app
  contacts_api:
    build:
      context: contacts_service
      dockerfile: Dockerfile.dev
    environment:
      SIGNING_KEY: ghostbusters
      DATABASE_URL: postgresql://postgres:password@db:5432/contacts
      WAIT_HOSTS: db:5432
      REMINDERS_HOST: http://reminders_api:8000/
      PORT: 8002
    ports:
      - "8002:8000"
    volumes:
      - ./contacts_service:/app
  templates_api:
    build:
      context: templates_service
      dockerfile: Dockerfile.dev
    environment:
      SIGNING_KEY: ghostbusters
      DATABASE_URL: postgresql://postgres:password@db:5432/templates
      WAIT_HOSTS: db:5432
      PORT: 8003
    ports:
      - "8003:8000"
    volumes:
      - ./templates_service:/app
  email_service:
    build:
      context: email_service
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/reminders
      WAIT_HOSTS: db:5432
      PORT: 7999
      EMAIL_PASSWORD: $EMAIL_PASSWORD
      COMPILER_ROUTE: Jj94E9GRLl6a0pAjIjVp1jLG3LAdyagN
      REMINDERS_HOST: http://reminders_api:8000/
    ports:
      - "7999:8000"
    volumes:
      - ./email_service:/app
